version: '3.1'

services:
  postgres:
    image: postgres:10.6
    restart: always
    build: .
    envirinment:
      POSTGRES_PASSWORD: 12345
    ports:
     - 127.0.0.1:5432:5432

  adminer: 
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: "redis:alpine"

